package models

import (
	"time"
)

/*
Company
----------------
id:         int
name:       string
location:   string (optional)
url:        string (url optional)
note:       string (optional - markdown)
created_at: date_time (optional)
updated_at: date_time (optional)

has_many:   jobs (maybe)
has_many:   people (through applications)
*/

type Company struct {
	Id        int64     `json:"id"`   // generated by DB
	Name      string    `json:"name"` // only required field
	Location  string    `json:"location"`
	Url       string    `json:"url"`
	Note      string    `json:"note"`       // markdown
	CreatedAt time.Time `json:"created_at"` // generated if not supplied
	UpdatedAt time.Time `json:"updated_at"` // generated if not supplied
}
