package models

import (
	"github.com/jinzhu/gorm"
	"time"
)

type Interview struct {
	gorm.Model
	Id int64 `json:"id" gorm:"PRIMARY_KEY";"AUTO_INCREMENT" `
	// generated by DB
	Note string `sql:"type:text;" json:"note"`
	// markdown
	ScheduledAt time.Time `json:"created_at"`
	// generated if not supplied
	Length int64 `json:"length"`
	// in minutes
	Rating string `sql:"type:text;" json:"rating"`
	// emoji
	Type string `sql:"type:text;" json:"type"`
	// string enum (user created)
	CreatedAt time.Time `json:"created_at"`
	// generated if not supplied
	UpdatedAt time.Time `json:"updated_at"`
	// generated if not supplied

	JobId  int64    `json:"job_id"`
	Job    Job      `gorm:"foreignkey:JobId"`
	People []Person `gorm:"many2many:people_thanks_emails;"`
	// has and belongs to many jobs
}
